### ISSUE TITLE
increment counter error

### ISSUE THREAD

**Issue by jancm** [Geofferey/mgkdhelper#1]
The statement:
RETRIES=$RETRIES+1
will not do what you think it will. The statement as written will be processed as a string. This means that, assuming an initial value of 0, on the first pass RETRIES will have a value of "0+1". On the next pass "0+1+1". Then "0+1+1+1" and so on. Simplest way to fix it is to put a let statement in front:
let RETRIES=$RETRIES + 1
Any of the following would be valid. Start with let forms (using a instead of RETRIES for examples)
let a=a+1
let a=$a+1
let a+=1
let ++a
let a++
Note that the last 3 forms will not work with a $ in front of the variable.
Instead of using let you can instead enclose equations within double parentheses. Doing that allows (but doesn't require) whitespace in the equation. So:
((a = a + 1))
((a= $a+1))
((a+=1))
((a++))
((++a))
For counter increments I have a bias towards the ++ forms, but that's just personal preference.

Aside from that I'm attaching a modified script file. I overhauled the retry logic, if you want to use it. Problem with the existing logic, in my opinion:
1 - it would take 10 minutes to get through all 10 tries.
2 - on device where the Magisk daemon gets killed frequently but the phone isn't rebooted very often the log would still fill up, possibly excessively.
3 - I see you already noticed the missing reset counter.

So I added another while loop that only triggers if the Daemon needs to be restarted. Reduced the wait between restart attempts to 5 seconds. Rotate log file between current and one previous. Include a counter to see how many log files you've rotated through. Show retry count in the log both for success and failure.
Mostly tested. Couldn't test multiple RETRIES since, for me, restart works on first try every time.

Added txt extension to allow upload.
[mgkd-helper.txt](https://github.com/Geofferey/mgkdhelper/files/3279857/mgkd-helper.txt)

**Comment by Geofferey** [comment]
That's great! Since you really want to contribute you should FORK the repo, PULL from your fork, MODIFY, PUSH back & submit a pull request from your repo to mine. After I test everything I can accept it. That way ALL the changes you make will PROPERLY be credited to you. You seem to be very proficient in shell scripting. That's a valuable asset which can be demonstrated to potential employers & others with a github. Start now because I wish I did a long time ago  ;) .

I'll wait a bit before I add your new changes so you can do it yourself if you'd like.

BTW did you have an error using my increment counting method? I did a test by changing sleep to 1 and magiskd_chk () to pgrep mgiskd. I also set "magisk --daemon" to "magisk --daemon" and it quits after 10 tries. Maybe an issue with standards but it worked as intended.

**Comment by jancm** [comment]
Didn't try to run it with the error. Noticed it then verified via terminal emulator. Note that the contents are still a valid expression and can be evaluated. See the last 2 statements in the attached image. I'll have another look to see why it may have worked anyway.
![Screenshot_20190612-111834](https://user-images.githubusercontent.com/37051754/59364670-38466080-8d05-11e9-9ad3-32292f863447.jpg)

**Comment by jancm** [comment]
As to why it worked. Your using -eq for the comparison. When you do that it evaluates both sides as numeric. Since RETRIES had a valid expression stored it evaluates the expression and uses the result. If you had used = or == it would have failed. See attached image.
![Screenshot_20190612-113936](https://user-images.githubusercontent.com/37051754/59366195-e7843700-8d07-11e9-85b2-3233d078945a.jpg)
